name: nfl_library
description: NFL Roster & Rules introduction project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: any
  http: ^0.13.5
  shimmer:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # 画像の設定をここに書く
  assets:
     - images/nfl_logo/nfl_logo_resize.jpg
     - images/favorite_teams/San_Francisco_49ers_logo_mini.png
     - images/background_images/49ers_cover.jpg
     - images/background_images/bears_cover.jpg
     - images/background_images/bengals_cover.jpg
     - images/background_images/bills_cover.jpg
     - images/background_images/broncos_cover.jpg
     - images/background_images/browns_cover.jpg
     - images/background_images/buccaneers_cover.jpg
     - images/background_images/cardinals_cover.jpg
     - images/background_images/chargers_cover.jpg
     - images/background_images/chiefs_cover.jpg
     - images/background_images/colts_cover.jpg
     - images/background_images/cowboys_cover.jpg
     - images/background_images/dolphins_cover.jpg
     - images/background_images/eagles_cover.jpg
     - images/background_images/falcons_cover.jpg
     - images/background_images/giants_cover.jpg
     - images/background_images/jagars_cover.jpg
     - images/background_images/jets_cover.jpg
     - images/background_images/lions_cover.jpg
     - images/background_images/packers_cover.jpg
     - images/background_images/panthers_cover.jpg
     - images/background_images/patriots_cover.jpg
     - images/background_images/raiders_cover.jpg
     - images/background_images/rams_cover.jpg
     - images/background_images/ravens_cover.jpg
     - images/background_images/redskins_cover.jpg
     - images/background_images/saints_cover.jpg
     - images/background_images/seahawks_cover.jpg
     - images/background_images/steelers_cover.jpg
     - images/background_images/texans_cover.jpg
     - images/background_images/titans_cover.jpg
     - images/background_images/vikings_cover.jpg
     - images/icons/defence-logo-resize.png
     - images/icons/offence-logo-resize.jpg
     - images/logos/49ers.gif
     - images/logos/bears.gif
     - images/logos/bengals.gif
     - images/logos/bills.gif
     - images/logos/broncos.gif
     - images/logos/browns.gif
     - images/logos/buccaneers.gif
     - images/logos/cardinals.gif
     - images/logos/chargers.gif
     - images/logos/chiefs.gif
     - images/logos/colts.gif
     - images/logos/cowboys.gif
     - images/logos/dolphins.gif
     - images/logos/eagles.gif
     - images/logos/falcons.gif
     - images/logos/giants.gif
     - images/logos/jaguars.gif
     - images/logos/jets.gif
     - images/logos/lions.gif
     - images/logos/packers.gif
     - images/logos/panthers.gif
     - images/logos/patriots.gif
     - images/logos/raiders.gif
     - images/logos/rams.gif
     - images/logos/ravens.gif
     - images/logos/commanders.gif
     - images/logos/saints.gif
     - images/logos/seahawks.gif
     - images/logos/steelers.gif
     - images/logos/texans.gif
     - images/logos/titans.gif
     - images/logos/vikings.gif
     - images/icons/defence-logo-resize.png
     - images/icons/offence-logo-resize.jpg
  #   - images/a_dot_ham.jpeg

     - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  fonts:
    - family: Playfair_Display
      fonts:
        - asset: fonts/Playfair_Display/static/PlayfairDisplay-Black.ttf
        - asset: fonts/Playfair_Display/static/PlayfairDisplay-BlackItalic.ttf
        - asset: fonts/Playfair_Display/static/PlayfairDisplay-Bold.ttf
        - asset: fonts/Playfair_Display/static/PlayfairDisplay-Medium.ttf
        - asset: fonts/Playfair_Display/static/PlayfairDisplay-Regular.ttf
          weight: 100
        - asset: fonts/Playfair_Display/static/PlayfairDisplay-Black.ttf
        - asset: fonts/Playfair_Display/static/PlayfairDisplay-BlackItalic.ttf
        - asset: fonts/Playfair_Display/static/PlayfairDisplay-Bold.ttf
        - asset: fonts/Playfair_Display/static/PlayfairDisplay-Medium.ttf
        - asset: fonts/Playfair_Display/static/PlayfairDisplay-Regular.ttf
          weight: 300
        - asset: fonts/Playfair_Display/static/PlayfairDisplay-Black.ttf
        - asset: fonts/Playfair_Display/static/PlayfairDisplay-BlackItalic.ttf
        - asset: fonts/Playfair_Display/static/PlayfairDisplay-Bold.ttf
        - asset: fonts/Playfair_Display/static/PlayfairDisplay-Medium.ttf
        - asset: fonts/Playfair_Display/static/PlayfairDisplay-Regular.ttf
          weight: 500

    - family: Dancing_Script
      fonts:
        - asset: fonts/Dancing_Script/static/DancingScript-Bold.ttf
        - asset: fonts/Dancing_Script/static/DancingScript-Medium.ttf
        - asset: fonts/Dancing_Script/static/DancingScript-Regular.ttf
        - asset: fonts/Dancing_Script/static/DancingScript-SemiBold.ttf
          weight: 100
        - asset: fonts/Dancing_Script/static/DancingScript-Bold.ttf
        - asset: fonts/Dancing_Script/static/DancingScript-Medium.ttf
        - asset: fonts/Dancing_Script/static/DancingScript-Regular.ttf
        - asset: fonts/Dancing_Script/static/DancingScript-SemiBold.ttf
          weight: 300

    - family: Bebas_Neue
      fonts:
        - asset: fonts/Bebas_Neue/BebasNeue-Regular.ttf
          weight: 100

    - family: Bree_Serif
      fonts:
        - asset: fonts/Bree_Serif/BreeSerif-Regular.ttf
          weight: 100

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages